linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - misspell

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/M1ngdaXie/go-local-rag-email

issues:
  exclude-use-default: false
  max-same-issues: 0

run:
  timeout: 5m
  skip-dirs:
    - bin
    - vendor
